name: Build and Deploy
on:
  push:
    branches: [main] #main 브랜치에 push할 때마다 이 워크플로가 자동 실행
env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: docker-cicd-practice
  IMAGE_TAG: latest
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build JAR
        working-directory: ./demo #명령어를 실행할 위치 명시
        run: ./gradlew build -x test
      - name: Build and push Docker image
        working-directory: ./demo
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Force new ECS deployment
        run: |
          aws ecs update-service \
            --cluster ecs-fargate-practice-cluster \
            --service ecs-fargate-practice-service \
            --force-new-deployment \
            --region $AWS_REGION
      - name: Wait for deployment to stabilize
        run: |
          aws ecs wait services-stable \
            --cluster ecs-fargate-practice-cluster \
            --services ecs-fargate-practice-service \
            --region $AWS_REGION
